#!/usr/bin/env python

###
### This file is generated automatically by SALOME v9.10.0 with dump python functionality
###

import sys
import salome

salome.salome_init()
import salome_notebook
notebook = salome_notebook.NoteBook()
sys.path.insert(0, r'D:/00_MODELOS/GITHUB/Salome_Scripts/Manual_Models/03_SUAVIZACAO')

####################################################
##       Begin of NoteBook variables section      ##
####################################################
notebook.set("a", 12)
notebook.set("b", 25)
####################################################
##        End of NoteBook variables section       ##
####################################################
###
### GEOM component
###

import GEOM
from salome.geom import geomBuilder
import math
import SALOMEDS


geompy = geomBuilder.New()

geomObj_1 = geompy.MakeVertex(0, 0, 0)
geomObj_2 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_3 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_4 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_5 = geompy.MakeVertex(0, 0, 0)
geomObj_6 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_7 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_8 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_9 = geompy.MakeVertex(0, 0, 0)
geomObj_10 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_11 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_12 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_13 = geompy.MakeBoxDXDYDZ(100, 100, 10)
geomObj_14 = geompy.MakeBoxDXDYDZ(75, 75, 10)
geomObj_15 = geompy.MakePartition([geomObj_13], [geomObj_14], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_16 = geompy.GetSubShape(geomObj_15, [20])
geomObj_17 = geompy.GetSubShape(geomObj_15, [48])
geomObj_18 = geompy.MakeLineTwoPnt(geomObj_16, geomObj_17)
geomObj_19 = geompy.GetSubShape(geomObj_15, [22])
geomObj_20 = geompy.GetSubShape(geomObj_15, [55])
geomObj_21 = geompy.MakeLineTwoPnt(geomObj_19, geomObj_20)
geomObj_22 = geompy.MakeQuad2Edges(geomObj_18, geomObj_21)
geomObj_23 = geompy.MakePartition([geomObj_15], [geomObj_22], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_24 = geompy.CreateGroup(geomObj_23, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_24, [69, 45, 55, 72])
geomObj_25 = geompy.CreateGroup(geomObj_23, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_25, [34, 32])
[geomObj_24, geomObj_25] = geompy.GetExistingSubObjects(geomObj_23, False)
geomObj_26 = geompy.GetSubShape(geomObj_15, [19])
geomObj_27 = geompy.MakePlane(geomObj_16, geomObj_26, 2000)
geomObj_28 = geompy.GetSubShape(geomObj_15, [17])
geomObj_29 = geompy.GetSubShape(geomObj_15, [51])
geomObj_30 = geompy.MakePlane(geomObj_28, geomObj_29, 2000)
geomObj_31 = geompy.MakePartition([geomObj_15], [geomObj_27, geomObj_30], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_32 = geompy.CreateGroup(geomObj_31, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_32, [34, 32])
geomObj_33 = geompy.CreateGroup(geomObj_31, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_33, [79, 55, 96, 86, 45, 69])
[geomObj_32, geomObj_33] = geompy.GetExistingSubObjects(geomObj_31, False)
geomObj_34 = geompy.CreateGroup(geomObj_31, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_34, [68, 57, 98, 44, 78, 49, 71, 88, 40])
geompy.DifferenceIDs(geomObj_34, [68, 57, 98, 44, 78, 49, 71, 88, 40])
geompy.UnionIDs(geomObj_34, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
geompy.DifferenceIDs(geomObj_34, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
geompy.UnionIDs(geomObj_34, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
[geomObj_32, geomObj_33, geomObj_34] = geompy.GetExistingSubObjects(geomObj_31, False)
geomObj_35 = geompy.CreateGroup(geomObj_23, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_35, [49, 64, 44, 57, 40, 68])
[geomObj_24, geomObj_25, geomObj_35] = geompy.GetExistingSubObjects(geomObj_23, False)
geomObj_36 = geompy.GetSubShape(geomObj_31, [60])
geomObj_37 = geompy.GetSubShape(geomObj_31, [36])
geomObj_38 = geompy.MakeVertex(0, 0, 0)
geomObj_39 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_40 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_41 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_42 = geompy.MakeBoxDXDYDZ(100, 200, 10)
geomObj_43 = geompy.MakeBoxDXDYDZ(75, 150, 10)
geomObj_44 = geompy.MakePartition([geomObj_42], [geomObj_43], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_45 = geompy.GetSubShape(geomObj_44, [20])
geomObj_46 = geompy.GetSubShape(geomObj_44, [48])
geomObj_47 = geompy.MakeLineTwoPnt(geomObj_45, geomObj_46)
geomObj_48 = geompy.GetSubShape(geomObj_44, [22])
geomObj_49 = geompy.GetSubShape(geomObj_44, [55])
geomObj_50 = geompy.MakeLineTwoPnt(geomObj_48, geomObj_49)
geomObj_51 = geompy.MakeQuad2Edges(geomObj_47, geomObj_50)
geomObj_52 = geompy.MakePartition([geomObj_44], [geomObj_51], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_53 = geompy.CreateGroup(geomObj_52, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_53, [69, 45, 55, 72])
geomObj_54 = geompy.CreateGroup(geomObj_52, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_54, [34, 32])
[geomObj_53, geomObj_54] = geompy.GetExistingSubObjects(geomObj_52, False)
geomObj_55 = geompy.CreateGroup(geomObj_52, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_55, [49, 64, 44, 57, 40, 68])
[geomObj_53, geomObj_54, geomObj_55] = geompy.GetExistingSubObjects(geomObj_52, False)
geomObj_56 = geompy.GetSubShape(geomObj_44, [19])
geomObj_57 = geompy.MakePlane(geomObj_45, geomObj_56, 2000)
geomObj_58 = geompy.GetSubShape(geomObj_44, [17])
geomObj_59 = geompy.GetSubShape(geomObj_44, [51])
geomObj_60 = geompy.MakePlane(geomObj_58, geomObj_59, 2000)
geomObj_61 = geompy.MakePartition([geomObj_44], [geomObj_57, geomObj_60], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_62 = geompy.CreateGroup(geomObj_61, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_62, [34, 32])
geomObj_63 = geompy.CreateGroup(geomObj_61, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_63, [79, 55, 96, 86, 45, 69])
[geomObj_62, geomObj_63] = geompy.GetExistingSubObjects(geomObj_61, False)
geomObj_64 = geompy.CreateGroup(geomObj_61, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_64, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
[geomObj_62, geomObj_63, geomObj_64] = geompy.GetExistingSubObjects(geomObj_61, False)
geomObj_65 = geompy.MakeVertex(0, 0, 0)
geomObj_66 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_67 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_68 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_69 = geompy.MakeBoxDXDYDZ(100, 200, 10)
geomObj_70 = geompy.MakeBoxDXDYDZ(75, 150, 10)
geomObj_71 = geompy.MakePartition([geomObj_69], [geomObj_70], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_72 = geompy.GetSubShape(geomObj_71, [20])
geomObj_73 = geompy.GetSubShape(geomObj_71, [48])
geomObj_74 = geompy.MakeLineTwoPnt(geomObj_72, geomObj_73)
geomObj_75 = geompy.GetSubShape(geomObj_71, [22])
geomObj_76 = geompy.GetSubShape(geomObj_71, [55])
geomObj_77 = geompy.MakeLineTwoPnt(geomObj_75, geomObj_76)
geomObj_78 = geompy.MakeQuad2Edges(geomObj_74, geomObj_77)
geomObj_79 = geompy.MakePartition([geomObj_71], [geomObj_78], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_80 = geompy.CreateGroup(geomObj_79, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_80, [69, 45, 55, 72])
geomObj_81 = geompy.CreateGroup(geomObj_79, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_81, [34, 32])
[geomObj_80, geomObj_81] = geompy.GetExistingSubObjects(geomObj_79, False)
geomObj_82 = geompy.CreateGroup(geomObj_79, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_82, [49, 64, 44, 57, 40, 68])
[geomObj_80, geomObj_81, geomObj_82] = geompy.GetExistingSubObjects(geomObj_79, False)
geomObj_83 = geompy.GetSubShape(geomObj_71, [19])
geomObj_84 = geompy.MakePlane(geomObj_72, geomObj_83, 2000)
geomObj_85 = geompy.GetSubShape(geomObj_71, [17])
geomObj_86 = geompy.GetSubShape(geomObj_71, [51])
geomObj_87 = geompy.MakePlane(geomObj_85, geomObj_86, 2000)
geomObj_88 = geompy.MakePartition([geomObj_71], [geomObj_84, geomObj_87], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_89 = geompy.CreateGroup(geomObj_88, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_89, [34, 32])
geomObj_90 = geompy.CreateGroup(geomObj_88, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_90, [79, 55, 96, 86, 45, 69])
[geomObj_89, geomObj_90] = geompy.GetExistingSubObjects(geomObj_88, False)
geomObj_91 = geompy.CreateGroup(geomObj_88, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_91, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
[geomObj_89, geomObj_90, geomObj_91] = geompy.GetExistingSubObjects(geomObj_88, False)
geomObj_92 = geompy.MakeVertex(0, 0, 0)
geomObj_93 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_94 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_95 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_96 = geompy.MakeBoxDXDYDZ(100, 200, 10)
geomObj_97 = geompy.MakeBoxDXDYDZ(75, 150, 10)
geomObj_98 = geompy.MakePartition([geomObj_96], [geomObj_97], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_99 = geompy.GetSubShape(geomObj_98, [20])
geomObj_100 = geompy.GetSubShape(geomObj_98, [48])
geomObj_101 = geompy.MakeLineTwoPnt(geomObj_99, geomObj_100)
geomObj_102 = geompy.GetSubShape(geomObj_98, [22])
geomObj_103 = geompy.GetSubShape(geomObj_98, [55])
geomObj_104 = geompy.MakeLineTwoPnt(geomObj_102, geomObj_103)
geomObj_105 = geompy.MakeQuad2Edges(geomObj_101, geomObj_104)
geomObj_106 = geompy.MakePartition([geomObj_98], [geomObj_105], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_107 = geompy.CreateGroup(geomObj_106, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_107, [69, 45, 55, 72])
geomObj_108 = geompy.CreateGroup(geomObj_106, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_108, [34, 32])
[geomObj_107, geomObj_108] = geompy.GetExistingSubObjects(geomObj_106, False)
geomObj_109 = geompy.CreateGroup(geomObj_106, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_109, [49, 64, 44, 57, 40, 68])
[geomObj_107, geomObj_108, geomObj_109] = geompy.GetExistingSubObjects(geomObj_106, False)
geomObj_110 = geompy.GetSubShape(geomObj_98, [19])
geomObj_111 = geompy.MakePlane(geomObj_99, geomObj_110, 2000)
geomObj_112 = geompy.GetSubShape(geomObj_98, [17])
geomObj_113 = geompy.GetSubShape(geomObj_98, [51])
geomObj_114 = geompy.MakePlane(geomObj_112, geomObj_113, 2000)
geomObj_115 = geompy.MakePartition([geomObj_98], [geomObj_111, geomObj_114], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_116 = geompy.CreateGroup(geomObj_115, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_116, [34, 32])
geomObj_117 = geompy.CreateGroup(geomObj_115, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_117, [79, 55, 96, 86, 45, 69])
[geomObj_116, geomObj_117] = geompy.GetExistingSubObjects(geomObj_115, False)
geomObj_118 = geompy.CreateGroup(geomObj_115, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_118, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
[geomObj_116, geomObj_117, geomObj_118] = geompy.GetExistingSubObjects(geomObj_115, False)
geomObj_119 = geompy.MakeVertex(0, 0, 0)
geomObj_120 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_121 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_122 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_123 = geompy.MakeBoxDXDYDZ(100, 200, 10)
geomObj_124 = geompy.MakeBoxDXDYDZ(75, 150, 10)
geomObj_125 = geompy.MakePartition([geomObj_123], [geomObj_124], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_126 = geompy.GetSubShape(geomObj_125, [20])
geomObj_127 = geompy.GetSubShape(geomObj_125, [48])
geomObj_128 = geompy.MakeLineTwoPnt(geomObj_126, geomObj_127)
geomObj_129 = geompy.GetSubShape(geomObj_125, [22])
geomObj_130 = geompy.GetSubShape(geomObj_125, [55])
geomObj_131 = geompy.MakeLineTwoPnt(geomObj_129, geomObj_130)
geomObj_132 = geompy.MakeQuad2Edges(geomObj_128, geomObj_131)
geomObj_133 = geompy.MakePartition([geomObj_125], [geomObj_132], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_134 = geompy.CreateGroup(geomObj_133, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_134, [69, 45, 55, 72])
geomObj_135 = geompy.CreateGroup(geomObj_133, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_135, [34, 32])
[geomObj_134, geomObj_135] = geompy.GetExistingSubObjects(geomObj_133, False)
geomObj_136 = geompy.CreateGroup(geomObj_133, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_136, [49, 64, 44, 57, 40, 68])
[geomObj_134, geomObj_135, geomObj_136] = geompy.GetExistingSubObjects(geomObj_133, False)
geomObj_137 = geompy.GetSubShape(geomObj_125, [19])
geomObj_138 = geompy.MakePlane(geomObj_126, geomObj_137, 2000)
geomObj_139 = geompy.GetSubShape(geomObj_125, [17])
geomObj_140 = geompy.GetSubShape(geomObj_125, [51])
geomObj_141 = geompy.MakePlane(geomObj_139, geomObj_140, 2000)
geomObj_142 = geompy.MakePartition([geomObj_125], [geomObj_138, geomObj_141], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_143 = geompy.CreateGroup(geomObj_142, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_143, [34, 32])
geomObj_144 = geompy.CreateGroup(geomObj_142, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_144, [79, 55, 96, 86, 45, 69])
[geomObj_143, geomObj_144] = geompy.GetExistingSubObjects(geomObj_142, False)
geomObj_145 = geompy.CreateGroup(geomObj_142, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_145, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
[geomObj_143, geomObj_144, geomObj_145] = geompy.GetExistingSubObjects(geomObj_142, False)
geomObj_146 = geompy.MakeVertex(0, 0, 0)
geomObj_147 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_148 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_149 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_150 = geompy.MakeBoxDXDYDZ(100, 200, 10)
geomObj_151 = geompy.MakeBoxDXDYDZ(75, 150, 10)
geomObj_152 = geompy.MakePartition([geomObj_150], [geomObj_151], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_153 = geompy.GetSubShape(geomObj_152, [20])
geomObj_154 = geompy.GetSubShape(geomObj_152, [48])
geomObj_155 = geompy.MakeLineTwoPnt(geomObj_153, geomObj_154)
geomObj_156 = geompy.GetSubShape(geomObj_152, [22])
geomObj_157 = geompy.GetSubShape(geomObj_152, [55])
geomObj_158 = geompy.MakeLineTwoPnt(geomObj_156, geomObj_157)
geomObj_159 = geompy.MakeQuad2Edges(geomObj_155, geomObj_158)
geomObj_160 = geompy.MakePartition([geomObj_152], [geomObj_159], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_161 = geompy.CreateGroup(geomObj_160, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_161, [69, 45, 55, 72])
geomObj_162 = geompy.CreateGroup(geomObj_160, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_162, [34, 32])
[geomObj_161, geomObj_162] = geompy.GetExistingSubObjects(geomObj_160, False)
geomObj_163 = geompy.CreateGroup(geomObj_160, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_163, [49, 64, 44, 57, 40, 68])
[geomObj_161, geomObj_162, geomObj_163] = geompy.GetExistingSubObjects(geomObj_160, False)
geomObj_164 = geompy.GetSubShape(geomObj_152, [19])
geomObj_165 = geompy.MakePlane(geomObj_153, geomObj_164, 2000)
geomObj_166 = geompy.GetSubShape(geomObj_152, [17])
geomObj_167 = geompy.GetSubShape(geomObj_152, [51])
geomObj_168 = geompy.MakePlane(geomObj_166, geomObj_167, 2000)
geomObj_169 = geompy.MakePartition([geomObj_152], [geomObj_165, geomObj_168], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_170 = geompy.CreateGroup(geomObj_169, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_170, [34, 32])
geomObj_171 = geompy.CreateGroup(geomObj_169, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_171, [79, 55, 96, 86, 45, 69])
[geomObj_170, geomObj_171] = geompy.GetExistingSubObjects(geomObj_169, False)
geomObj_172 = geompy.CreateGroup(geomObj_169, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_172, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
[geomObj_170, geomObj_171, geomObj_172] = geompy.GetExistingSubObjects(geomObj_169, False)
geomObj_173 = geompy.MakeVertex(0, 0, 0)
geomObj_174 = geompy.MakeVectorDXDYDZ(1, 0, 0)
geomObj_175 = geompy.MakeVectorDXDYDZ(0, 1, 0)
geomObj_176 = geompy.MakeVectorDXDYDZ(0, 0, 1)
geomObj_177 = geompy.MakeBoxDXDYDZ(100, 200, 10)
geomObj_178 = geompy.MakeBoxDXDYDZ(75, 150, 10)
geomObj_179 = geompy.MakePartition([geomObj_177], [geomObj_178], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_180 = geompy.GetSubShape(geomObj_179, [20])
geomObj_181 = geompy.GetSubShape(geomObj_179, [48])
geomObj_182 = geompy.MakeLineTwoPnt(geomObj_180, geomObj_181)
geomObj_183 = geompy.GetSubShape(geomObj_179, [22])
geomObj_184 = geompy.GetSubShape(geomObj_179, [55])
geomObj_185 = geompy.MakeLineTwoPnt(geomObj_183, geomObj_184)
geomObj_186 = geompy.MakeQuad2Edges(geomObj_182, geomObj_185)
geomObj_187 = geompy.MakePartition([geomObj_179], [geomObj_186], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_188 = geompy.CreateGroup(geomObj_187, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_188, [69, 45, 55, 72])
geomObj_189 = geompy.CreateGroup(geomObj_187, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_189, [34, 32])
[geomObj_188, geomObj_189] = geompy.GetExistingSubObjects(geomObj_187, False)
geomObj_190 = geompy.CreateGroup(geomObj_187, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_190, [49, 64, 44, 57, 40, 68])
[geomObj_188, geomObj_189, geomObj_190] = geompy.GetExistingSubObjects(geomObj_187, False)
geomObj_191 = geompy.GetSubShape(geomObj_179, [19])
geomObj_192 = geompy.MakePlane(geomObj_180, geomObj_191, 2000)
geomObj_193 = geompy.GetSubShape(geomObj_179, [17])
geomObj_194 = geompy.GetSubShape(geomObj_179, [51])
geomObj_195 = geompy.MakePlane(geomObj_193, geomObj_194, 2000)
geomObj_196 = geompy.MakePartition([geomObj_179], [geomObj_192, geomObj_195], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
geomObj_197 = geompy.CreateGroup(geomObj_196, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_197, [34, 32])
geomObj_198 = geompy.CreateGroup(geomObj_196, geompy.ShapeType["FACE"])
geompy.UnionIDs(geomObj_198, [79, 55, 96, 86, 45, 69])
[geomObj_197, geomObj_198] = geompy.GetExistingSubObjects(geomObj_196, False)
geomObj_199 = geompy.CreateGroup(geomObj_196, geompy.ShapeType["EDGE"])
geompy.UnionIDs(geomObj_199, [68, 57, 98, 44, 78, 49, 71, 88, 40, 95, 90, 64])
[geomObj_197, geomObj_198, geomObj_199] = geompy.GetExistingSubObjects(geomObj_196, False)
Box_1 = geompy.MakeBoxDXDYDZ(10, 10, 10)
face = geompy.CreateGroup(Box_1, geompy.ShapeType["FACE"])
geompy.UnionIDs(face, [33])
[face] = geompy.GetExistingSubObjects(Box_1, False)
geompy.addToStudy( Box_1, 'Box_1' )
geompy.addToStudyInFather( Box_1, face, 'face' )

###
### SMESH component
###

import  SMESH, SALOMEDS
from salome.smesh import smeshBuilder

smesh = smeshBuilder.New()
#smesh.SetEnablePublish( False ) # Set to False to avoid publish in study if not needed or in some particular situations:
                                 # multiples meshes built in parallel, complex and numerous mesh edition (performance)

Regular_1D_4 = smesh.CreateHypothesis('Regular_1D')
NumberOfSegments_10 = smesh.CreateHypothesis('NumberOfSegments')
NumberOfSegments_10.SetReversedEdges( [] )
NumberOfSegments_10.SetObjectEntry( "0:1:2:58" )
Quadrangle_2D_5 = smesh.CreateHypothesis('Quadrangle_2D')
Hexa_3D_6 = smesh.CreateHypothesis('Hexa_3D')
QuadrangleParams_QUAD_QU_1_ = smesh.CreateHypothesis('QuadrangleParams')
QuadrangleParams_QUAD_QU_1_.SetQuadType( smeshBuilder.QUAD_QUADRANGLE_PREF_REVERSED )
QuadrangleParams_QUAD_QU_1_.SetEnforcedNodes( [], [] )
NumberOfSegments_5_0 = smesh.CreateHypothesis('NumberOfSegments')
NumberOfSegments_5_0.SetNumberOfSegments( 5 )
NumberOfSegments_5_0.SetReversedEdges( [] )
NumberOfSegments_5_0.SetObjectEntry( "0:1:2:58" )
QuadrangleParams_QUAD_QU_1__1 = smesh.CreateHypothesis('QuadrangleParams')
QuadrangleParams_QUAD_QU_1__1.SetQuadType( smeshBuilder.QUAD_QUADRANGLE_PREF )
QuadrangleParams_QUAD_QU_1__1.SetTriaVertex( -1 )
QuadrangleParams_QUAD_QU_1__1.SetEnforcedNodes( [], [] )
NumberOfSegments_10_1 = smesh.CreateHypothesis('NumberOfSegments')
NumberOfSegments_10_1.SetNumberOfSegments( 10 )
NumberOfSegments_10_1.SetReversedEdges( [] )
NumberOfSegments_10_1.SetObjectEntry( "0:1:2:58" )
QuadrangleParams_QUAD_QU_1__2 = smesh.CreateHypothesis('QuadrangleParams')
QuadrangleParams_QUAD_QU_1__2.SetQuadType( smeshBuilder.QUAD_QUADRANGLE_PREF )
QuadrangleParams_QUAD_QU_1__2.SetTriaVertex( -1 )
QuadrangleParams_QUAD_QU_1__2.SetEnforcedNodes( [], [] )
NumberOfSegments_10.SetNumberOfSegments( 4 )
NumberOfSegments_10_2 = smesh.CreateHypothesis('NumberOfSegments')
NumberOfSegments_10_2.SetReversedEdges( [] )
NumberOfSegments_10_2.SetObjectEntry( "0:1:2:72" )
QuadrangleParams_QUAD_QU_1__3 = smesh.CreateHypothesis('QuadrangleParams')
QuadrangleParams_QUAD_QU_1__3.SetQuadType( smeshBuilder.QUAD_QUADRANGLE_PREF )
QuadrangleParams_QUAD_QU_1__3.SetEnforcedNodes( [], [] )
NumberOfSegments_10_2.SetNumberOfSegments( 5 )
NumberOfSegments_10_3 = smesh.CreateHypothesis('NumberOfSegments')
NumberOfSegments_10_3.SetNumberOfSegments( 10 )
NumberOfSegments_10_3.SetReversedEdges( [] )
NumberOfSegments_10_3.SetObjectEntry( "0:1:2:86" )
NumberOfSegments_5_0_1 = smesh.CreateHypothesis('NumberOfSegments')
NumberOfSegments_5_0_1.SetNumberOfSegments( 5 )
NumberOfSegments_5_0_1.SetReversedEdges( [] )
NumberOfSegments_5_0_1.SetObjectEntry( "0:1:2:86" )
NumberOfSegments_10_4 = smesh.CreateHypothesis('NumberOfSegments')
NumberOfSegments_10_4.SetNumberOfSegments( 10 )
NumberOfSegments_10_4.SetReversedEdges( [] )
NumberOfSegments_10_4.SetObjectEntry( "0:1:2:100" )
NumberOfSegments_5_0_2 = smesh.CreateHypothesis('NumberOfSegments')
NumberOfSegments_5_0_2.SetNumberOfSegments( 5 )
NumberOfSegments_5_0_2.SetReversedEdges( [] )
NumberOfSegments_5_0_2.SetObjectEntry( "0:1:2:100" )
Number_of_Segments_1 = smesh.CreateHypothesis('NumberOfSegments')
Number_of_Segments_1.SetNumberOfSegments( 5 )
Quadrangle_Parameters_1 = smesh.CreateHypothesis('QuadrangleParams')
Quadrangle_Parameters_1.SetQuadType( smeshBuilder.QUAD_TRIANGLE_PREF )
Quadrangle_Parameters_1.SetTriaVertex( -1 )
Quadrangle_Parameters_1.SetEnforcedNodes( [], [] )
Mesh_1 = smesh.Mesh(Box_1,'Mesh_1')
status = Mesh_1.AddHypothesis(Number_of_Segments_1)
status = Mesh_1.AddHypothesis(Regular_1D_4)
status = Mesh_1.AddHypothesis(Quadrangle_Parameters_1)
status = Mesh_1.AddHypothesis(Quadrangle_2D_5)
status = Mesh_1.AddHypothesis(Hexa_3D_6)
face_1 = Mesh_1.GroupOnGeom(face,'face',SMESH.FACE)
isDone = Mesh_1.Compute()
[ face_1 ] = Mesh_1.GetGroups()
Number_of_Segments_2 = smesh.CreateHypothesis('NumberOfSegments')
Number_of_Segments_2.SetNumberOfSegments( 10 )
status = Mesh_1.AddHypothesis(Regular_1D_4,face)
status = Mesh_1.AddHypothesis(Number_of_Segments_2,face)
isDone = Mesh_1.Compute()
[ face_1 ] = Mesh_1.GetGroups()
Sub_mesh_1 = Mesh_1.GetSubMesh( face, 'Sub-mesh_1' )


## Set names of Mesh objects
smesh.SetName(face_1, 'face')
smesh.SetName(Mesh_1.GetMesh(), 'Mesh_1')
smesh.SetName(Sub_mesh_1, 'Sub-mesh_1')
smesh.SetName(Regular_1D_4, 'Regular_1D_4')
smesh.SetName(Number_of_Segments_2, 'Number of Segments_2')
smesh.SetName(Quadrangle_2D_5, 'Quadrangle_2D_5')
smesh.SetName(Quadrangle_Parameters_1, 'Quadrangle Parameters_1')
smesh.SetName(Hexa_3D_6, 'Hexa_3D_6')
smesh.SetName(Number_of_Segments_1, 'Number of Segments_1')
smesh.SetName(NumberOfSegments_5_0_2, 'NumberOfSegments=5,[],0:1:2:100')
smesh.SetName(NumberOfSegments_10_4, 'NumberOfSegments=10,[],0:1:2:100')
smesh.SetName(NumberOfSegments_5_0_1, 'NumberOfSegments=5,[],0:1:2:86')
smesh.SetName(NumberOfSegments_10_3, 'NumberOfSegments=10,[],0:1:2:86')
smesh.SetName(QuadrangleParams_QUAD_QU_1__3, 'QuadrangleParams=QUAD_QU...,-1,[],[]')
smesh.SetName(NumberOfSegments_10, 'NumberOfSegments=10,[],0:1:2:58')
smesh.SetName(QuadrangleParams_QUAD_QU_1_, 'QuadrangleParams=QUAD_QU...,-1,[],[]')
smesh.SetName(NumberOfSegments_5_0, 'NumberOfSegments=5,[],0:1:2:58')
smesh.SetName(QuadrangleParams_QUAD_QU_1__1, 'QuadrangleParams=QUAD_QU...,-1,[],[]')
smesh.SetName(NumberOfSegments_10_1, 'NumberOfSegments=10,[],0:1:2:58')
smesh.SetName(QuadrangleParams_QUAD_QU_1__2, 'QuadrangleParams=QUAD_QU...,-1,[],[]')
smesh.SetName(NumberOfSegments_10_2, 'NumberOfSegments=10,[],0:1:2:72')


if salome.sg.hasDesktop():
  salome.sg.updateObjBrowser()
