#!/usr/bin/env python

###
### This file is generated automatically by SALOME v9.10.0 with dump python functionality
###

import sys
import salome

salome.salome_init()
import salome_notebook
notebook = salome_notebook.NoteBook()
sys.path.insert(0, r'C:/Users/Lenovo/00_MODELOS/00_TREINO_SOFTWARE/00_CURSO_WIKKI/01_CURSO_SALOME/SALOME_SCRIPTS')


### GEOM component
###

import GEOM
from salome.geom import geomBuilder
import math
import SALOMEDS


geompy = geomBuilder.New()

O = geompy.MakeVertex(0, 0, 0)
OX = geompy.MakeVectorDXDYDZ(1, 0, 0)
OY = geompy.MakeVectorDXDYDZ(0, 1, 0)
OZ = geompy.MakeVectorDXDYDZ(0, 0, 1)
Vertex_1 = geompy.MakeVertex(0, 5, 0)
Vertex_2 = geompy.MakeVertex(0, 0, 5)
Arc_1 = geompy.MakeArcCenter(O, Vertex_1, Vertex_2,False)
Vertex_3 = geompy.MakeVertex(0, 0, 20)
Vertex_4 = geompy.MakeVertex(0, 20, 0)
Arc_2 = geompy.MakeArcCenter(O, Vertex_3, Vertex_4,False)
Arc_2_vertex_2 = geompy.GetSubShape(Arc_2, [2])
Arc_1_vertex_3 = geompy.GetSubShape(Arc_1, [3])
Line_1 = geompy.MakeLineTwoPnt(Arc_2_vertex_2, Arc_1_vertex_3)
Arc_2_vertex_3 = geompy.GetSubShape(Arc_2, [3])
Arc_1_vertex_2 = geompy.GetSubShape(Arc_1, [2])
Line_2 = geompy.MakeLineTwoPnt(Arc_2_vertex_3, Arc_1_vertex_2)
Multi_Rotation_1 = geompy.MultiRotate1DByStep(Line_2, OX, 22.5*math.pi/180.0, 4)
Multi_Rotation_1_edge_11 = geompy.GetSubShape(Multi_Rotation_1, [11])
Multi_Rotation_1_edge_5 = geompy.GetSubShape(Multi_Rotation_1, [5])
Vertex_7 = geompy.MakeVertex(0.2, 0, 5)
Vertex_8 = geompy.MakeVertex(0.2, -0, 20)
Vertex_9 = geompy.MakeVertex(0.2, 5, -0)
Vertex_10 = geompy.MakeVertex(0.2, 20, 0)
Vertex_11 = geompy.MakeVertex(0.2, 0, 0)
Line_3 = geompy.MakeLineTwoPnt(Vertex_7, Vertex_8)
Line_4 = geompy.MakeLineTwoPnt(Vertex_10, Vertex_9)
geompy.Rotate(Line_3, OX, -5*math.pi/180.0)
geompy.Rotate(Line_4, OX, 5*math.pi/180.0)
Line_3_vertex_2 = geompy.GetSubShape(Line_3, [2])
Line_4_vertex_3 = geompy.GetSubShape(Line_4, [3])
Arc_3 = geompy.MakeArcCenter(Vertex_11, Line_3_vertex_2, Line_4_vertex_3,False)
Line_3_vertex_3 = geompy.GetSubShape(Line_3, [3])
Line_4_vertex_2 = geompy.GetSubShape(Line_4, [2])
Arc_4 = geompy.MakeArcCenter(Vertex_11, Line_3_vertex_3, Line_4_vertex_2,False)
Face_2 = geompy.MakeFaceWires([Line_3, Line_4, Arc_3, Arc_4], 1)
Extrusion_2 = geompy.MakePrismVecH(Face_2, OX, 0.6)
Cylinder_1 = geompy.MakeCylinderRHA(20, 1, 45*math.pi/180.)
Cylinder_2 = geompy.MakeCylinderRHA(5, 1, 45*math.pi/180.)
Cut_2 = geompy.MakeCutList(Cylinder_1, [Cylinder_2], True)
Cylinder_3 = geompy.MakeCylinderRHA(20, 0.6, 45*math.pi/180.)
geompy.TranslateDXDYDZ(Cylinder_3, 0, 0, 0.2)
Rotation_1 = geompy.MakeRotation(Cylinder_3, OZ, 5*math.pi/180.0)
Cylinder_4 = geompy.MakeCylinderRH(1.5, 1)
geompy.TranslateDXDYDZ(Cylinder_4, 12.5, 0, 0)
geompy.Rotate(Cylinder_4, OZ, 22.5*math.pi/180.0)
Cut_3 = geompy.MakeCutList(Cut_2, [Rotation_1, Cylinder_4], True)
Cut_3_face_21 = geompy.GetSubShape(Cut_3, [21])
Mirror_1 = geompy.MakeMirrorByPlane(Cut_3, Cut_3_face_21)
Fuse_1 = geompy.MakeFuseList([Cut_3, Mirror_1], True, True)
Fuse_1_vertex_18 = geompy.GetSubShape(Fuse_1, [18])
Fuse_1_vertex_16 = geompy.GetSubShape(Fuse_1, [16])
Line_5 = geompy.MakeLineTwoPnt(O, Fuse_1_vertex_16)
Vertex_12 = geompy.MakeVertex(0, 12.5, 0)
Vertex_13 = geompy.MakeVertex(0, 10, 0)
Vertex_14 = geompy.MakeVertex(0, 15, 0)
geompy.Rotate(Vertex_12, OZ, -22.5*math.pi/180.0)
geompy.Rotate(Line_5, OZ, -5*math.pi/180.0)
geompy.Rotate(Vertex_13, OZ, -5*math.pi/180.0)
geompy.Rotate(Vertex_14, OZ, -5*math.pi/180.0)
Rotation_2_1 = geompy.MakeRotation(Line_5, OZ, -35*math.pi/180.0)
Rotation_2_2 = geompy.MakeRotation(Vertex_13, OZ, -35*math.pi/180.0)
Rotation_2_3 = geompy.MakeRotation(Vertex_14, OZ, -35*math.pi/180.0)
Arc_5 = geompy.MakeArcCenter(O, Vertex_13, Rotation_2_2,False)
Arc_6 = geompy.MakeArcCenter(O, Vertex_14, Rotation_2_3,False)
Arc_5_vertex_3 = geompy.GetSubShape(Arc_5, [3])
Line_6 = geompy.MakeLineTwoPnt(Arc_5_vertex_3, Vertex_12)
Line_6_vertex_3 = geompy.GetSubShape(Line_6, [3])
Arc_6_vertex_3 = geompy.GetSubShape(Arc_6, [3])
Line_7 = geompy.MakeLineTwoPnt(Line_6_vertex_3, Arc_6_vertex_3)
Arc_6_vertex_2 = geompy.GetSubShape(Arc_6, [2])
Line_8 = geompy.MakeLineTwoPnt(Line_6_vertex_3, Arc_6_vertex_2)
Arc_5_vertex_2 = geompy.GetSubShape(Arc_5, [2])
Line_9 = geompy.MakeLineTwoPnt(Line_6_vertex_3, Arc_5_vertex_2)
Rotation_2_4 = geompy.MakeRotation(Line_5, OZ, -45*math.pi/180.0)
Rotation_2_5 = geompy.MakeRotation(Rotation_2_1, OZ, -45*math.pi/180.0)
Rotation_2_6 = geompy.MakeRotation(Arc_5, OZ, -45*math.pi/180.0)
Rotation_2_7 = geompy.MakeRotation(Arc_6, OZ, -45*math.pi/180.0)
Rotation_2_8 = geompy.MakeRotation(Line_6, OZ, -45*math.pi/180.0)
Rotation_2_9 = geompy.MakeRotation(Line_7, OZ, -45*math.pi/180.0)
Rotation_2_10 = geompy.MakeRotation(Line_8, OZ, -45*math.pi/180.0)
Rotation_2_11 = geompy.MakeRotation(Line_9, OZ, -45*math.pi/180.0)
Extrusion_3 = geompy.MakePrismVecH(Line_5, OZ, 1)
Extrusion_4 = geompy.MakePrismVecH(Rotation_2_1, OZ, 1)
Extrusion_5 = geompy.MakePrismVecH(Arc_5, OZ, 1)
Extrusion_6 = geompy.MakePrismVecH(Arc_6, OZ, 1)
Extrusion_7 = geompy.MakePrismVecH(Line_6, OZ, 1)
Extrusion_8 = geompy.MakePrismVecH(Line_7, OZ, 1)
Extrusion_9 = geompy.MakePrismVecH(Line_8, OZ, 1)
Extrusion_10 = geompy.MakePrismVecH(Line_9, OZ, 1)
Extrusion_11 = geompy.MakePrismVecH(Rotation_2_4, OZ, 1)
Extrusion_12 = geompy.MakePrismVecH(Rotation_2_5, OZ, 1)
Extrusion_13 = geompy.MakePrismVecH(Rotation_2_6, OZ, 1)
Extrusion_14 = geompy.MakePrismVecH(Rotation_2_7, OZ, 1)
Extrusion_15 = geompy.MakePrismVecH(Rotation_2_8, OZ, 1)
Extrusion_16 = geompy.MakePrismVecH(Rotation_2_9, OZ, 1)
Extrusion_17 = geompy.MakePrismVecH(Rotation_2_10, OZ, 1)
Extrusion_18 = geompy.MakePrismVecH(Rotation_2_11, OZ, 1)
Fuse_1_face_22 = geompy.GetSubShape(Fuse_1, [22])
Plane_1 = geompy.MakePlaneFace(Fuse_1_face_22, 25)
Fuse_1_face_40 = geompy.GetSubShape(Fuse_1, [40])
Plane_2 = geompy.MakePlaneFace(Fuse_1_face_40, 25)
Partition_1 = geompy.MakePartition([Fuse_1], [Extrusion_3, Extrusion_4, Extrusion_5, Extrusion_6, Extrusion_7, Extrusion_8, Extrusion_9, Extrusion_10, Extrusion_11, Extrusion_12, Extrusion_13, Extrusion_14, Extrusion_15, Extrusion_16, Extrusion_17, Extrusion_18, Plane_1, Plane_2], [], [], geompy.ShapeType["SOLID"], 0, [], 0)
NoExtraEdges_1 = geompy.RemoveExtraEdges(Partition_1, True)
UnionFaces_1 = geompy.UnionFaces(NoExtraEdges_1)
linha_0_2 = geompy.CreateGroup(UnionFaces_1, geompy.ShapeType["EDGE"])
geompy.UnionIDs(linha_0_2, [147, 11, 588, 648, 270, 535, 670, 219, 687, 491, 422, 82, 94, 106, 585, 259, 433, 55, 245, 463, 494, 460, 70, 497, 542, 242, 144, 515, 607, 171, 514, 566, 61, 295, 477, 423, 364, 561, 470, 220, 118, 20, 185, 6, 38, 428, 52, 457, 474, 163, 704, 340, 132, 58, 653, 454])
linha_0_6 = geompy.CreateGroup(UnionFaces_1, geompy.ShapeType["EDGE"])
geompy.UnionIDs(linha_0_6, [302, 323, 381, 315, 310, 395, 378, 374])
linha_05 = geompy.CreateGroup(UnionFaces_1, geompy.ShapeType["EDGE"])
geompy.UnionIDs(linha_05, [504, 216, 450, 276, 46, 36, 29, 540, 23, 530, 306, 386, 101, 33, 41, 264, 123, 511, 390, 141, 556, 31, 620, 414, 436, 304, 80, 486, 104, 16, 626, 448, 482, 77, 632, 18, 125, 388, 308, 25, 618, 484, 49, 569, 139, 48, 426, 209])
linha_15 = geompy.CreateGroup(UnionFaces_1, geompy.ShapeType["EDGE"])
geompy.UnionIDs(linha_15, [383, 272, 267, 129, 318, 134, 479, 443])
geompy.DifferenceIDs(linha_05, [504, 216, 450, 276, 46, 36, 29, 540, 23, 530, 306, 386, 101, 33, 41, 264, 123, 511, 390, 141, 556, 31, 620, 414, 436, 304, 80, 486, 104, 16, 626, 448, 482, 77, 632, 18, 125, 388, 308, 25, 618, 484, 49, 569, 139, 48, 426, 209])
geompy.UnionIDs(linha_05, [504, 216, 450, 276, 46, 36, 29, 540, 23, 530, 306, 386, 101, 33, 41, 264, 123, 511, 390, 141, 556, 31, 620, 414, 436, 304, 80, 486, 104, 16, 626, 448, 482, 77, 632, 18, 125, 388, 308, 25, 618, 484, 49, 569, 139, 48, 426, 209, 727, 590, 332, 714, 724, 717, 405, 402, 247, 641, 578, 235, 651, 337, 156])
geompy.DifferenceIDs(linha_05, [504, 216, 450, 276, 46, 36, 29, 540, 23, 530, 306, 386, 101, 33, 41, 264, 123, 511, 390, 141, 556, 31, 620, 414, 436, 304, 80, 486, 104, 16, 626, 448, 482, 77, 632, 18, 125, 388, 308, 25, 618, 484, 49, 569, 139, 48, 426, 209, 727, 590, 332, 714, 724, 717, 405, 402, 247, 641, 578, 235, 651, 337, 156])
geompy.UnionIDs(linha_05, [504, 216, 450, 276, 46, 36, 29, 540, 23, 530, 306, 386, 101, 33, 41, 264, 123, 511, 390, 141, 556, 31, 620, 414, 436, 304, 80, 486, 104, 16, 626, 448, 482, 77, 632, 18, 125, 388, 308, 25, 618, 484, 49, 569, 139, 48, 426, 209, 727, 590, 332, 714, 724, 717, 405, 402, 247, 641, 578, 235, 651, 337, 156])
diagonais = geompy.CreateGroup(UnionFaces_1, geompy.ShapeType["EDGE"])
geompy.UnionIDs(diagonais, [237, 707, 639, 362, 285, 646, 178, 593, 680, 330, 183, 250, 240, 335, 656, 643, 668, 663, 168, 154, 580, 610, 576, 290, 583, 158, 600, 699, 233, 685, 161, 357])
arco_05 = geompy.CreateGroup(UnionFaces_1, geompy.ShapeType["EDGE"])
geompy.UnionIDs(arco_05, [323, 118, 433, 378, 460, 470, 472, 94, 313, 275, 137, 374, 392, 127, 302, 376, 265, 395, 463, 261, 474, 270, 320, 446, 132, 70, 310, 381, 257, 451, 147, 454, 116, 259, 120, 315, 488, 477, 220, 497])
arco_10 = geompy.CreateGroup(UnionFaces_1, geompy.ShapeType["EDGE"])
geompy.UnionIDs(arco_10, [619, 535, 55, 623, 617, 58, 27, 629, 514, 428, 561, 11, 44, 13, 6, 9])
arco_35 = geompy.CreateGroup(UnionFaces_1, geompy.ShapeType["EDGE"])
geompy.UnionIDs(arco_35, [68, 185, 431, 72, 96, 92, 521, 508, 588, 416, 697, 552, 188, 665, 537, 367, 85, 359, 109, 554, 690, 605, 212, 528, 195, 559, 75, 602, 507, 213, 350, 682, 564, 532, 196, 223, 545, 673, 702, 518, 99, 287, 180, 412, 419, 347, 202, 199, 226, 292])
[linha_0_2, linha_0_6, linha_05, linha_15, diagonais, arco_05, arco_10, arco_35] = geompy.GetExistingSubObjects(UnionFaces_1, False)
geompy.DifferenceIDs(arco_05, [323, 118, 433, 378, 460, 470, 472, 94, 313, 275, 137, 374, 392, 127, 302, 376, 265, 395, 463, 261, 474, 270, 320, 446, 132, 70, 310, 381, 257, 451, 147, 454, 116, 259, 120, 315, 488, 477, 220, 497])
geompy.UnionIDs(arco_05, [472, 313, 275, 137, 392, 127, 376, 265, 261, 320, 446, 257, 451, 116, 120, 488])
geompy.DifferenceIDs(arco_10, [619, 535, 55, 623, 617, 58, 27, 629, 514, 428, 561, 11, 44, 13, 6, 9])
geompy.UnionIDs(arco_10, [619, 623, 617, 27, 629, 44, 13, 9])
geompy.DifferenceIDs(arco_35, [68, 185, 431, 72, 96, 92, 521, 508, 588, 416, 697, 552, 188, 665, 537, 367, 85, 359, 109, 554, 690, 605, 212, 528, 195, 559, 75, 602, 507, 213, 350, 682, 564, 532, 196, 223, 545, 673, 702, 518, 99, 287, 180, 412, 419, 347, 202, 199, 226, 292])
geompy.UnionIDs(arco_35, [68, 431, 72, 96, 92, 521, 508, 416, 697, 552, 188, 665, 537, 367, 85, 359, 109, 554, 690, 605, 212, 528, 195, 559, 75, 602, 507, 213, 350, 682, 564, 532, 196, 223, 545, 673, 702, 518, 99, 287, 180, 412, 419, 347, 202, 199, 226, 292])
geompy.DifferenceIDs(arco_35, [68, 431, 72, 96, 92, 521, 508, 416, 697, 552, 188, 665, 537, 367, 85, 359, 109, 554, 690, 605, 212, 528, 195, 559, 75, 602, 507, 213, 350, 682, 564, 532, 196, 223, 545, 673, 702, 518, 99, 287, 180, 412, 419, 347, 202, 199, 226, 292])
geompy.UnionIDs(arco_35, [68, 431, 72, 96, 92, 521, 508, 416, 697, 552, 188, 665, 537, 367, 85, 359, 109, 554, 690, 605, 212, 528, 195, 559, 75, 602, 507, 213, 350, 682, 564, 532, 196, 223, 545, 673, 702, 518, 99, 287, 180, 412, 419, 347, 202, 199, 226, 292])
geompy.DifferenceIDs(linha_05, [504, 216, 450, 276, 46, 36, 29, 540, 23, 530, 306, 386, 101, 33, 41, 264, 123, 511, 390, 141, 556, 31, 620, 414, 436, 304, 80, 486, 104, 16, 626, 448, 482, 77, 632, 18, 125, 388, 308, 25, 618, 484, 49, 569, 139, 48, 426, 209, 727, 590, 332, 714, 724, 717, 405, 402, 247, 641, 578, 235, 651, 337, 156])
geompy.UnionIDs(linha_05, [504, 216, 450, 276, 46, 36, 29, 540, 23, 530, 306, 386, 101, 33, 41, 264, 123, 511, 390, 141, 556, 31, 620, 414, 436, 304, 80, 486, 104, 16, 626, 448, 482, 77, 632, 18, 125, 388, 308, 25, 618, 484, 49, 569, 139, 48, 426, 209, 727, 590, 332, 714, 724, 717, 405, 402, 247, 641, 578, 235, 651, 337, 156, 166])
geompy.addToStudy( O, 'O' )
geompy.addToStudy( OX, 'OX' )
geompy.addToStudy( OY, 'OY' )
geompy.addToStudy( OZ, 'OZ' )
geompy.addToStudy( Vertex_1, 'Vertex_1' )
geompy.addToStudy( Vertex_2, 'Vertex_2' )
geompy.addToStudy( Arc_1, 'Arc_1' )
geompy.addToStudy( Vertex_3, 'Vertex_3' )
geompy.addToStudy( Vertex_4, 'Vertex_4' )
geompy.addToStudy( Arc_2, 'Arc_2' )
geompy.addToStudyInFather( Arc_2, Arc_2_vertex_2, 'Arc_2:vertex_2' )
geompy.addToStudyInFather( Arc_1, Arc_1_vertex_3, 'Arc_1:vertex_3' )
geompy.addToStudy( Line_1, 'Line_1' )
geompy.addToStudyInFather( Arc_2, Arc_2_vertex_3, 'Arc_2:vertex_3' )
geompy.addToStudyInFather( Arc_1, Arc_1_vertex_2, 'Arc_1:vertex_2' )
geompy.addToStudy( Line_2, 'Line_2' )
geompy.addToStudy( Multi_Rotation_1, 'Multi-Rotation_1' )
geompy.addToStudyInFather( Multi_Rotation_1, Multi_Rotation_1_edge_11, 'Multi-Rotation_1:edge_11' )
geompy.addToStudyInFather( Multi_Rotation_1, Multi_Rotation_1_edge_5, 'Multi-Rotation_1:edge_5' )
geompy.addToStudy( Vertex_7, 'Vertex_7' )
geompy.addToStudy( Vertex_8, 'Vertex_8' )
geompy.addToStudy( Vertex_9, 'Vertex_9' )
geompy.addToStudy( Vertex_10, 'Vertex_10' )
geompy.addToStudy( Vertex_11, 'Vertex_11' )
geompy.addToStudy( Line_3, 'Line_3' )
geompy.addToStudy( Line_4, 'Line_4' )
geompy.addToStudyInFather( Line_3, Line_3_vertex_2, 'Line_3:vertex_2' )
geompy.addToStudyInFather( Line_4, Line_4_vertex_3, 'Line_4:vertex_3' )
geompy.addToStudy( Arc_3, 'Arc_3' )
geompy.addToStudyInFather( Line_3, Line_3_vertex_3, 'Line_3:vertex_3' )
geompy.addToStudyInFather( Line_4, Line_4_vertex_2, 'Line_4:vertex_2' )
geompy.addToStudy( Arc_4, 'Arc_4' )
geompy.addToStudy( Face_2, 'Face_2' )
geompy.addToStudy( Cylinder_1, 'Cylinder_1' )
geompy.addToStudy( Extrusion_2, 'Extrusion_2' )
geompy.addToStudy( Cylinder_2, 'Cylinder_2' )
geompy.addToStudy( Cut_2, 'Cut_2' )
geompy.addToStudy( Cylinder_3, 'Cylinder_3' )
geompy.addToStudy( Rotation_1, 'Rotation_1' )
geompy.addToStudy( Cylinder_4, 'Cylinder_4' )
geompy.addToStudy( Cut_3, 'Cut_3' )
geompy.addToStudyInFather( Cut_3, Cut_3_face_21, 'Cut_3:face_21' )
geompy.addToStudy( Mirror_1, 'Mirror_1' )
geompy.addToStudy( Fuse_1, 'Fuse_1' )
geompy.addToStudyInFather( Fuse_1, Fuse_1_vertex_18, 'Fuse_1:vertex_18' )
geompy.addToStudyInFather( Fuse_1, Fuse_1_vertex_16, 'Fuse_1:vertex_16' )
geompy.addToStudy( Line_5, 'Line_5' )
geompy.addToStudy( Vertex_12, 'Vertex_12' )
geompy.addToStudy( Vertex_13, 'Vertex_13' )
geompy.addToStudy( Vertex_14, 'Vertex_14' )
geompy.addToStudy( Rotation_2_1, 'Rotation_2_1' )
geompy.addToStudy( Rotation_2_2, 'Rotation_2_2' )
geompy.addToStudy( Rotation_2_3, 'Rotation_2_3' )
geompy.addToStudy( Arc_5, 'Arc_5' )
geompy.addToStudy( Arc_6, 'Arc_6' )
geompy.addToStudyInFather( Arc_5, Arc_5_vertex_3, 'Arc_5:vertex_3' )
geompy.addToStudy( Line_6, 'Line_6' )
geompy.addToStudyInFather( Line_6, Line_6_vertex_3, 'Line_6:vertex_3' )
geompy.addToStudyInFather( Arc_6, Arc_6_vertex_3, 'Arc_6:vertex_3' )
geompy.addToStudy( Line_7, 'Line_7' )
geompy.addToStudyInFather( Arc_6, Arc_6_vertex_2, 'Arc_6:vertex_2' )
geompy.addToStudy( Line_8, 'Line_8' )
geompy.addToStudyInFather( Arc_5, Arc_5_vertex_2, 'Arc_5:vertex_2' )
geompy.addToStudy( Line_9, 'Line_9' )
geompy.addToStudy( Rotation_2_4, 'Rotation_2_4' )
geompy.addToStudy( Rotation_2_5, 'Rotation_2_5' )
geompy.addToStudy( Rotation_2_6, 'Rotation_2_6' )
geompy.addToStudy( Rotation_2_7, 'Rotation_2_7' )
geompy.addToStudy( Rotation_2_8, 'Rotation_2_8' )
geompy.addToStudy( Rotation_2_9, 'Rotation_2_9' )
geompy.addToStudy( Rotation_2_10, 'Rotation_2_10' )
geompy.addToStudy( Rotation_2_11, 'Rotation_2_11' )
geompy.addToStudy( Extrusion_3, 'Extrusion_3' )
geompy.addToStudy( Extrusion_4, 'Extrusion_4' )
geompy.addToStudy( Extrusion_5, 'Extrusion_5' )
geompy.addToStudy( Extrusion_6, 'Extrusion_6' )
geompy.addToStudy( Extrusion_7, 'Extrusion_7' )
geompy.addToStudy( Extrusion_8, 'Extrusion_8' )
geompy.addToStudy( Extrusion_9, 'Extrusion_9' )
geompy.addToStudy( Extrusion_10, 'Extrusion_10' )
geompy.addToStudy( Extrusion_11, 'Extrusion_11' )
geompy.addToStudy( Extrusion_12, 'Extrusion_12' )
geompy.addToStudy( Extrusion_13, 'Extrusion_13' )
geompy.addToStudy( Extrusion_14, 'Extrusion_14' )
geompy.addToStudy( Extrusion_15, 'Extrusion_15' )
geompy.addToStudy( Extrusion_16, 'Extrusion_16' )
geompy.addToStudy( Extrusion_17, 'Extrusion_17' )
geompy.addToStudy( Extrusion_18, 'Extrusion_18' )
geompy.addToStudyInFather( Fuse_1, Fuse_1_face_22, 'Fuse_1:face_22' )
geompy.addToStudy( Plane_1, 'Plane_1' )
geompy.addToStudyInFather( Fuse_1, Fuse_1_face_40, 'Fuse_1:face_40' )
geompy.addToStudy( Plane_2, 'Plane_2' )
geompy.addToStudy( Partition_1, 'Partition_1' )
geompy.addToStudy( NoExtraEdges_1, 'NoExtraEdges_1' )
geompy.addToStudy( UnionFaces_1, 'UnionFaces_1' )
geompy.addToStudyInFather( UnionFaces_1, linha_0_6, 'linha_0.6' )
geompy.addToStudyInFather( UnionFaces_1, linha_0_2, 'linha_0.2' )
geompy.addToStudyInFather( UnionFaces_1, linha_05, 'linha_05' )
geompy.addToStudyInFather( UnionFaces_1, linha_15, 'linha_15' )
geompy.addToStudyInFather( UnionFaces_1, diagonais, 'diagonais' )
geompy.addToStudyInFather( UnionFaces_1, arco_05, 'arco_05' )
geompy.addToStudyInFather( UnionFaces_1, arco_10, 'arco_10' )
geompy.addToStudyInFather( UnionFaces_1, arco_35, 'arco_35' )

### Folders and it's content
Modo_1 = geompy.NewFolder('Modo_1')
geompy.PutToFolder(Vertex_1, Modo_1)
geompy.PutToFolder(Vertex_2, Modo_1)
geompy.PutToFolder(Arc_1, Modo_1)
geompy.PutToFolder(Vertex_3, Modo_1)
geompy.PutToFolder(Vertex_4, Modo_1)
geompy.PutToFolder(Arc_2, Modo_1)
geompy.PutToFolder(Line_1, Modo_1)
geompy.PutToFolder(Line_2, Modo_1)
geompy.PutToFolder(Multi_Rotation_1, Modo_1)
geompy.PutToFolder(geompy.PutToFolder(geompy.PutToFolder(geompy.PutToFolder(geompy.PutToFolder(geompy.PutToFolder(geompy.PutToFolder(Vertex_7, Modo_1)
geompy.PutToFolder(Vertex_8, Modo_1)
geompy.PutToFolder(Vertex_9, Modo_1)
geompy.PutToFolder(Vertex_10, Modo_1)
geompy.PutToFolder(Vertex_11, Modo_1)
geompy.PutToFolder(Line_3, Modo_1)
geompy.PutToFolder(Line_4, Modo_1)
geompy.PutToFolder(Arc_3, Modo_1)
geompy.PutToFolder(Arc_4, Modo_1)
geompy.PutToFolder(Face_2, Modo_1)
geompy.PutToFolder(Extrusion_2, Modo_1)
geompy.PutToFolder(Modo_2 = geompy.NewFolder('Modo_2')
geompy.PutToFolder(Cylinder_1, Modo_2)
geompy.PutToFolder(Cylinder_2, Modo_2)
geompy.PutToFolder(Cut_2, Modo_2)
geompy.PutToFolder(Cylinder_3, Modo_2)
geompy.PutToFolder(Rotation_1, Modo_2)
geompy.PutToFolder(Cylinder_4, Modo_2)
geompy.PutToFolder(Cut_3, Modo_2)
geompy.PutToFolder(Mirror_1, Modo_2)
geompy.PutToFolder(Fuse_1, Modo_2)
geompy.PutToFolder(Line_5, Modo_2)
geompy.PutToFolder(Vertex_12, Modo_2)
geompy.PutToFolder(Vertex_13, Modo_2)
geompy.PutToFolder(Vertex_14, Modo_2)
geompy.PutToFolder(Rotation_2_1, Modo_2)
geompy.PutToFolder(Rotation_2_2, Modo_2)
geompy.PutToFolder(Rotation_2_3, Modo_2)
geompy.PutToFolder(Arc_5, Modo_2)
geompy.PutToFolder(Arc_6, Modo_2)
geompy.PutToFolder(Line_6, Modo_2)
geompy.PutToFolder(Line_7, Modo_2)
geompy.PutToFolder(Line_8, Modo_2)
geompy.PutToFolder(Line_9, Modo_2)
geompy.PutToFolder(Rotation_2_4, Modo_2)
geompy.PutToFolder(Rotation_2_5, Modo_2)
geompy.PutToFolder(Rotation_2_6, Modo_2)
geompy.PutToFolder(Rotation_2_7, Modo_2)
geompy.PutToFolder(Rotation_2_8, Modo_2)
geompy.PutToFolder(Rotation_2_9, Modo_2)
geompy.PutToFolder(Rotation_2_10, Modo_2)
geompy.PutToFolder(Rotation_2_11, Modo_2)
geompy.PutToFolder(Extrusion_3, Modo_2)
geompy.PutToFolder(Extrusion_4, Modo_2)
geompy.PutToFolder(Extrusion_5, Modo_2)
geompy.PutToFolder(Extrusion_6, Modo_2)
geompy.PutToFolder(Extrusion_7, Modo_2)
geompy.PutToFolder(Extrusion_8, Modo_2)
geompy.PutToFolder(Extrusion_9, Modo_2)
geompy.PutToFolder(Extrusion_10, Modo_2)
geompy.PutToFolder(Extrusion_11, Modo_2)
geompy.PutToFolder(Extrusion_12, Modo_2)
geompy.PutToFolder(Extrusion_13, Modo_2)
geompy.PutToFolder(Extrusion_14, Modo_2)
geompy.PutToFolder(Extrusion_15, Modo_2)
geompy.PutToFolder(Extrusion_16, Modo_2)
geompy.PutToFolder(Extrusion_17, Modo_2)
geompy.PutToFolder(Extrusion_18, Modo_2)
geompy.PutToFolder(Plane_1, Modo_2)
geompy.PutToFolder(Plane_2, Modo_2)
geompy.PutToFolder(Partition_1, Modo_2)

###
### SMESH component
###

import  SMESH, SALOMEDS
from salome.smesh import smeshBuilder

smesh = smeshBuilder.New()
#smesh.SetEnablePublish( False ) # Set to False to avoid publish in study if not needed or in some particular situations:
                                 # multiples meshes built in parallel, complex and numerous mesh edition (performance)

Number_of_Segments_1 = smesh.CreateHypothesis('NumberOfSegments')
Number_of_Segments_1.SetNumberOfSegments( 15 )
smeshObj_1 = smesh.Mesh(Partition_1)
status = smeshObj_1.AddHypothesis(Number_of_Segments_1)
Regular_1D = smesh.CreateHypothesis('Regular_1D')
status = smeshObj_1.AddHypothesis(Regular_1D)
Quadrangle_2D = smesh.CreateHypothesis('Quadrangle_2D')
status = smeshObj_1.AddHypothesis(Quadrangle_2D)
Hexa_3D = smesh.CreateHypothesis('Hexa_3D')
status = smeshObj_1.AddHypothesis(Hexa_3D)
isDone = smeshObj_1.Compute()
a2 = smesh.CreateHypothesis('NumberOfSegments')
a2.SetNumberOfSegments( 2 )
Number_of_Segments_2 = smesh.CreateHypothesis('NumberOfSegments')
Number_of_Segments_2.SetNumberOfSegments( 15 )
Mesh_1 = smesh.Mesh(UnionFaces_1,'Mesh_1')
status = Mesh_1.AddHypothesis(Number_of_Segments_2)
status = Mesh_1.AddHypothesis(Regular_1D)
status = Mesh_1.AddHypothesis(Quadrangle_2D)
status = Mesh_1.AddHypothesis(Hexa_3D)
linha_0_2_1 = Mesh_1.GroupOnGeom(linha_0_2,'linha_0.2',SMESH.EDGE)
linha_0_6_1 = Mesh_1.GroupOnGeom(linha_0_6,'linha_0.6',SMESH.EDGE)
linha_05_1 = Mesh_1.GroupOnGeom(linha_05,'linha_05',SMESH.EDGE)
linha_15_1 = Mesh_1.GroupOnGeom(linha_15,'linha_15',SMESH.EDGE)
diagonais_1 = Mesh_1.GroupOnGeom(diagonais,'diagonais',SMESH.EDGE)
arco_05_1 = Mesh_1.GroupOnGeom(arco_05,'arco_05',SMESH.EDGE)
arco_10_1 = Mesh_1.GroupOnGeom(arco_10,'arco_10',SMESH.EDGE)
arco_35_1 = Mesh_1.GroupOnGeom(arco_35,'arco_35',SMESH.EDGE)
a2_1 = smesh.CreateHypothesis('NumberOfSegments')
a2_1.SetNumberOfSegments( 2 )
linha_0_2_2 = Mesh_1.GetSubMesh( linha_0_2, 'linha_0.2' )
status = Mesh_1.AddHypothesis(Regular_1D,linha_0_2)
status = Mesh_1.AddHypothesis(a2_1,linha_0_2)
a6 = smesh.CreateHypothesis('NumberOfSegments')
a6.SetNumberOfSegments( 6 )
status = Mesh_1.AddHypothesis(Regular_1D,linha_0_6)
status = Mesh_1.AddHypothesis(a6,linha_0_6)
a10 = smesh.CreateHypothesis('NumberOfSegments')
a10.SetNumberOfSegments( 10 )
status = Mesh_1.AddHypothesis(Regular_1D,linha_05)
status = Mesh_1.AddHypothesis(a10,linha_05)
a30 = smesh.CreateHypothesis('NumberOfSegments')
a30.SetNumberOfSegments( 30 )
status = Mesh_1.AddHypothesis(Regular_1D,linha_15)
status = Mesh_1.AddHypothesis(a30,linha_15)
a5 = smesh.CreateHypothesis('NumberOfSegments')
a5.SetNumberOfSegments( 5 )
status = Mesh_1.AddHypothesis(Regular_1D,diagonais)
status = Mesh_1.AddHypothesis(a5,diagonais)
status = Mesh_1.AddHypothesis(Regular_1D,arco_05)
status = Mesh_1.AddHypothesis(a2,arco_05)
arco_2 = smesh.CreateHypothesis('NumberOfSegments')
arco_2.SetNumberOfSegments( 2 )
status = Mesh_1.RemoveHypothesis(a2,arco_05)
status = Mesh_1.AddHypothesis(arco_2,arco_05)
arco_4 = smesh.CreateHypothesis('NumberOfSegments')
arco_4.SetNumberOfSegments( 4 )
status = Mesh_1.AddHypothesis(Regular_1D,arco_10)
status = Mesh_1.AddHypothesis(arco_4,arco_10)
arco_10_2 = smesh.CreateHypothesis('NumberOfSegments')
arco_10_2.SetNumberOfSegments( 10 )
arco_35_2 = Mesh_1.GetSubMesh( arco_35, 'Sub-mesh_1' )
status = Mesh_1.AddHypothesis(Regular_1D,arco_35)
status = Mesh_1.AddHypothesis(arco_10_2,arco_35)
isDone = Mesh_1.Compute()
[ linha_0_2_1, linha_0_6_1, linha_05_1, linha_15_1, diagonais_1, arco_05_1, arco_10_1, arco_35_1 ] = Mesh_1.GetGroups()
Mesh_1.Clear()
isDone = Mesh_1.Compute()
[ linha_0_2_1, linha_0_6_1, linha_05_1, linha_15_1, diagonais_1, arco_05_1, arco_10_1, arco_35_1 ] = Mesh_1.GetGroups()
Number_of_Segments_2.SetNumberOfSegments( 15 )
Mesh_1.Clear()
isDone = Mesh_1.Compute()
[ linha_0_2_1, linha_0_6_1, linha_05_1, linha_15_1, diagonais_1, arco_05_1, arco_10_1, arco_35_1 ] = Mesh_1.GetGroups()
arco_35_3 = smesh.CreateHypothesis('NumberOfSegments')
arco_35_3.SetNumberOfSegments( 10 )
status = Mesh_1.RemoveHypothesis(arco_10_2,arco_35)
status = Mesh_1.AddHypothesis(arco_35_3,arco_35)
isDone = Mesh_1.SetMeshOrder( [ [ arco_35_2, linha_0_2_2 ] ])
Mesh_1.Clear()
isDone = Mesh_1.Compute()
[ linha_0_2_1, linha_0_6_1, linha_05_1, linha_15_1, diagonais_1, arco_05_1, arco_10_1, arco_35_1 ] = Mesh_1.GetGroups()
isDone = Mesh_1.Compute()
[ linha_0_2_1, linha_0_6_1, linha_05_1, linha_15_1, diagonais_1, arco_05_1, arco_10_1, arco_35_1 ] = Mesh_1.GetGroups()
Mesh_1.Clear()
isDone = Mesh_1.Compute()
[ linha_0_2_1, linha_0_6_1, linha_05_1, linha_15_1, diagonais_1, arco_05_1, arco_10_1, arco_35_1 ] = Mesh_1.GetGroups()
Mesh_1_rotated = Mesh_1.RotateObjectMakeMesh( Mesh_1, SMESH.AxisStruct( 0, 0, 0, 0, 0, 1 ), 1.5708, 0, 'Mesh_1_rotated' )
isDone = Mesh_1_rotated.Compute()
Mesh_1_mirrored = Mesh_1.MirrorObjectMakeMesh( Mesh_1, SMESH.AxisStruct( 0, 0, 0, 0, 1, 0 ), SMESH.SMESH_MeshEditor.PLANE, 0, 'Mesh_1_mirrored' )
Mesh_1_rotated_mirrored = Mesh_1_rotated.MirrorObjectMakeMesh( Mesh_1_rotated, SMESH.AxisStruct( 0, 0, 0, 0, 1, 0 ), SMESH.SMESH_MeshEditor.PLANE, 0, 'Mesh_1_rotated_mirrored' )
isDone = Mesh_1_rotated_mirrored.Compute()
isDone = Mesh_1_mirrored.Compute()
Compound_Mesh_1 = smesh.Concatenate( [ Mesh_1.GetMesh(), Mesh_1_rotated.GetMesh(), Mesh_1_mirrored.GetMesh(), Mesh_1_rotated_mirrored.GetMesh() ], 1, 1, 1e-05, False )
[ Group_24_0, Group_25_1, Group_26_2, Group_27_3, Group_28_4, Group_29_5, Group_30_6, Group_31_7 ] = Compound_Mesh_1.GetGroups()
linha_0_6_2 = Mesh_1.GetSubMesh( linha_0_6, 'linha_0.6' )
linha_05_2 = Mesh_1.GetSubMesh( linha_05, 'linha_05' )
linha_15_2 = Mesh_1.GetSubMesh( linha_15, 'linha_15' )
diagonais_2 = Mesh_1.GetSubMesh( diagonais, 'diagonais' )
arco_05_2 = Mesh_1.GetSubMesh( arco_05, 'arco_05' )
arco_10_3 = Mesh_1.GetSubMesh( arco_10, 'arco_10' )

## some objects were removed
aStudyBuilder = salome.myStudy.NewBuilder()
SO = salome.myStudy.FindObjectIOR(salome.myStudy.ConvertObjectToIOR(smeshObj_1.GetMesh()))
if SO: aStudyBuilder.RemoveObjectWithChildren(SO)

## Set names of Mesh objects
smesh.SetName(linha_0_2_1, 'linha_0.2')
smesh.SetName(Regular_1D, 'Regular_1D')
smesh.SetName(Hexa_3D, 'Hexa_3D')
smesh.SetName(Quadrangle_2D, 'Quadrangle_2D')
smesh.SetName(a2, '2')
smesh.SetName(Number_of_Segments_2, 'Number of Segments_2')
smesh.SetName(Number_of_Segments_1, 'Number of Segments_1')
smesh.SetName(a10, '10')
smesh.SetName(a30, '30')
smesh.SetName(arco_35_2, 'arco_35')
smesh.SetName(a2_1, '2')
smesh.SetName(a6, '6')
smesh.SetName(linha_15_2, 'linha_15')
smesh.SetName(a5, '5')
smesh.SetName(diagonais_2, 'diagonais')
smesh.SetName(arco_2, 'arco_2')
smesh.SetName(arco_05_2, 'arco_05')
smesh.SetName(arco_10_3, 'arco_10')
smesh.SetName(Compound_Mesh_1.GetMesh(), 'Compound_Mesh_1')
smesh.SetName(linha_0_2_2, 'linha_0.2')
smesh.SetName(linha_0_6_2, 'linha_0.6')
smesh.SetName(linha_05_2, 'linha_05')
smesh.SetName(Mesh_1_rotated.GetMesh(), 'Mesh_1_rotated')
smesh.SetName(Mesh_1.GetMesh(), 'Mesh_1')
smesh.SetName(Mesh_1_rotated_mirrored.GetMesh(), 'Mesh_1_rotated_mirrored')
smesh.SetName(Mesh_1_mirrored.GetMesh(), 'Mesh_1_mirrored')
smesh.SetName(arco_35_3, 'arco_35')
smesh.SetName(arco_10_2, 'arco_10')
smesh.SetName(arco_4, 'arco_4')
smesh.SetName(Group_25_1, 'Group 25 1')
smesh.SetName(Group_26_2, 'Group 26 2')
smesh.SetName(Group_24_0, 'Group 24 0')
smesh.SetName(Group_29_5, 'Group 29 5')
smesh.SetName(Group_30_6, 'Group 30 6')
smesh.SetName(Group_27_3, 'Group 27 3')
smesh.SetName(Group_28_4, 'Group 28 4')
smesh.SetName(Group_31_7, 'Group 31 7')
smesh.SetName(arco_35_1, 'arco_35')
smesh.SetName(arco_05_1, 'arco_05')
smesh.SetName(arco_10_1, 'arco_10')
smesh.SetName(linha_15_1, 'linha_15')
smesh.SetName(diagonais_1, 'diagonais')
smesh.SetName(linha_0_6_1, 'linha_0.6')
smesh.SetName(linha_05_1, 'linha_05')


if salome.sg.hasDesktop():
  salome.sg.updateObjBrowser()
